# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BasePayPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BasePayPb.proto',
  package='BasePay',
  serialized_pb=_b('\n\x0f\x42\x61sePayPb.proto\x12\x07\x42\x61sePay\"\xbc\x01\n\x07\x42\x61sePay\x12\x11\n\tchannelId\x18\x01 \x01(\t\x12\x11\n\tnotifyurl\x18\x02 \x02(\t\x12\x13\n\x0bproductName\x18\x03 \x01(\t\x12\x13\n\x0bproductDesc\x18\x04 \x01(\t\x12\x13\n\x0bpartnercode\x18\x05 \x02(\t\x12\x12\n\nappversion\x18\x06 \x02(\t\x12\x14\n\x0c\x63urrencyName\x18\x07 \x01(\t\x12\x0c\n\x04rate\x18\x08 \x02(\x02\x12\x14\n\x0cpartnerorder\x18\t \x02(\tB\"\n\x11\x63om.nearme.pluginB\rBasePayEntity')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BASEPAY = _descriptor.Descriptor(
  name='BasePay',
  full_name='BasePay.BasePay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channelId', full_name='BasePay.BasePay.channelId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notifyurl', full_name='BasePay.BasePay.notifyurl', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productName', full_name='BasePay.BasePay.productName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productDesc', full_name='BasePay.BasePay.productDesc', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnercode', full_name='BasePay.BasePay.partnercode', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appversion', full_name='BasePay.BasePay.appversion', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currencyName', full_name='BasePay.BasePay.currencyName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='BasePay.BasePay.rate', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerorder', full_name='BasePay.BasePay.partnerorder', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['BasePay'] = _BASEPAY

BasePay = _reflection.GeneratedProtocolMessageType('BasePay', (_message.Message,), dict(
  DESCRIPTOR = _BASEPAY,
  __module__ = 'BasePayPb_pb2'
  # @@protoc_insertion_point(class_scope:BasePay.BasePay)
  ))
_sym_db.RegisterMessage(BasePay)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.nearme.pluginB\rBasePayEntity'))
# @@protoc_insertion_point(module_scope)
