# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BaseResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BaseResult.proto',
  package='BaseResult',
  serialized_pb=_b('\n\x10\x42\x61seResult.proto\x12\nBaseResult\"_\n\nBaseResult\x12\x0c\n\x04\x63ode\x18\x01 \x02(\t\x12\x0b\n\x03msg\x18\x02 \x02(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x14\n\x0c\x64iscountInfo\x18\x04 \x01(\t\x12\x0f\n\x07payType\x18\x05 \x01(\tB%\n\x11\x63om.nearme.pluginB\x10\x42\x61seResultEntity')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BASERESULT = _descriptor.Descriptor(
  name='BaseResult',
  full_name='BaseResult.BaseResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='BaseResult.BaseResult.code', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='BaseResult.BaseResult.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='BaseResult.BaseResult.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discountInfo', full_name='BaseResult.BaseResult.discountInfo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='BaseResult.BaseResult.payType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['BaseResult'] = _BASERESULT

BaseResult = _reflection.GeneratedProtocolMessageType('BaseResult', (_message.Message,), dict(
  DESCRIPTOR = _BASERESULT,
  __module__ = 'BaseResult_pb2'
  # @@protoc_insertion_point(class_scope:BaseResult.BaseResult)
  ))
_sym_db.RegisterMessage(BaseResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.nearme.pluginB\020BaseResultEntity'))
# @@protoc_insertion_point(module_scope)
