# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceContactPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import BaseResult_pb2
from . import BaseHeader_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServiceContactPb.proto',
  package='ServiceContact',
  serialized_pb=_b('\n\x16ServiceContactPb.proto\x12\x0eServiceContact\x1a\x10\x42\x61seResult.proto\x1a\x10\x42\x61seHeader.proto\"\x98\x01\n\x07Request\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.BaseHeader.BaseHeader\x12\x30\n\x07\x63hannel\x18\x02 \x01(\x0e\x32\x1f.ServiceContact.Request.Channel\x12\r\n\x05\x62izNo\x18\x03 \x01(\t\"$\n\x07\x43hannel\x12\x07\n\x03_0P\x10\x00\x12\x07\n\x03_1P\x10\x01\x12\x07\n\x03_2P\x10\x02\"\xe1\x02\n\x06Result\x12*\n\nbaseresult\x18\x01 \x02(\x0b\x32\x16.BaseResult.BaseResult\x12\x34\n\x0bserviceType\x18\x02 \x01(\x0e\x32\x1f.ServiceContact.Result.ServType\x12\x13\n\x0bserviceDesc\x18\x03 \x01(\t\x12\x16\n\x0eserviceContent\x18\x04 \x01(\t\x12\x0f\n\x07telDesc\x18\x05 \x01(\t\x12\x12\n\ntelContent\x18\x06 \x01(\t\x12\x11\n\temailDesc\x18\x07 \x01(\t\x12\x14\n\x0c\x65mailContent\x18\x08 \x01(\t\x12\x15\n\ruserGuideFlag\x18\t \x01(\x08\x12\x14\n\x0cuserGuideUrl\x18\n \x01(\t\x12\x12\n\nuserAppKey\x18\x0b \x01(\t\x12\x11\n\tuserAppId\x18\x0c \x01(\t\"&\n\x08ServType\x12\x07\n\x03TEL\x10\x00\x12\t\n\x05\x45MAIL\x10\x01\x12\x06\n\x02QQ\x10\x02\x42+\n\x11\x63om.nearme.pluginB\x16ServiceContactPbEntity')
  ,
  dependencies=[BaseResult_pb2.DESCRIPTOR,BaseHeader_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_CHANNEL = _descriptor.EnumDescriptor(
  name='Channel',
  full_name='ServiceContact.Request.Channel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_0P', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='_1P', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='_2P', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=195,
  serialized_end=231,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_CHANNEL)

_RESULT_SERVTYPE = _descriptor.EnumDescriptor(
  name='ServType',
  full_name='ServiceContact.Result.ServType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QQ', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=549,
  serialized_end=587,
)
_sym_db.RegisterEnumDescriptor(_RESULT_SERVTYPE)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='ServiceContact.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ServiceContact.Request.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='ServiceContact.Request.channel', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bizNo', full_name='ServiceContact.Request.bizNo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_CHANNEL,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=231,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='ServiceContact.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseresult', full_name='ServiceContact.Result.baseresult', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceType', full_name='ServiceContact.Result.serviceType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceDesc', full_name='ServiceContact.Result.serviceDesc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceContent', full_name='ServiceContact.Result.serviceContent', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telDesc', full_name='ServiceContact.Result.telDesc', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telContent', full_name='ServiceContact.Result.telContent', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emailDesc', full_name='ServiceContact.Result.emailDesc', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emailContent', full_name='ServiceContact.Result.emailContent', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userGuideFlag', full_name='ServiceContact.Result.userGuideFlag', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userGuideUrl', full_name='ServiceContact.Result.userGuideUrl', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userAppKey', full_name='ServiceContact.Result.userAppKey', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userAppId', full_name='ServiceContact.Result.userAppId', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESULT_SERVTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=587,
)

_REQUEST.fields_by_name['header'].message_type = BaseHeader_pb2._BASEHEADER
_REQUEST.fields_by_name['channel'].enum_type = _REQUEST_CHANNEL
_REQUEST_CHANNEL.containing_type = _REQUEST
_RESULT.fields_by_name['baseresult'].message_type = BaseResult_pb2._BASERESULT
_RESULT.fields_by_name['serviceType'].enum_type = _RESULT_SERVTYPE
_RESULT_SERVTYPE.containing_type = _RESULT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'ServiceContactPb_pb2'
  # @@protoc_insertion_point(class_scope:ServiceContact.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'ServiceContactPb_pb2'
  # @@protoc_insertion_point(class_scope:ServiceContact.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.nearme.pluginB\026ServiceContactPbEntity'))
# @@protoc_insertion_point(module_scope)
