# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DirectPay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb_src.python_standard import BaseHeaderOut_pb2
from pb_src.python_standard import Product_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DirectPay.proto',
  package='',
  serialized_pb=_b('\n\x0f\x44irectPay.proto\x1a\x13\x42\x61seHeaderOut.proto\x1a\rProduct.proto\"\xfe\x03\n\x10\x44irectPayRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x14\n\x0cpartnerOrder\x18\x02 \x02(\t\x12\x11\n\tpartnerId\x18\x03 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x02(\t\x12\x0f\n\x07payType\x18\x05 \x02(\t\x12\x0f\n\x07\x63hannel\x18\x06 \x02(\t\x12\x11\n\tpayAmount\x18\x07 \x02(\t\x12\x10\n\x08\x63urrency\x18\x08 \x02(\t\x12 \n\x18isCocoinRechargeAndSpend\x18\t \x02(\x08\x12\x19\n\x07product\x18\x0b \x02(\x0b\x32\x08.Product\x12\x11\n\tnotifyUrl\x18\r \x01(\t\x12\x15\n\rpartnerParams\x18\x0e \x01(\t\x12\x14\n\x0c\x65xtendParams\x18\x0f \x01(\t\x12\x10\n\x08\x63ouponId\x18\x15 \x01(\t\x12\x16\n\x0e\x64iscountAmount\x18\x16 \x01(\t\x12\x13\n\x0bpointCardNo\x18\x19 \x01(\t\x12\x19\n\x11pointCardPassword\x18\x1a \x01(\t\x12\x19\n\x11hasAdditionalFees\x18\x1b \x01(\x08\x12\x0e\n\x06\x66\x61\x63tor\x18\x1c \x01(\t\x12\x15\n\rpayActivityId\x18\x1d \x01(\t\x12\x18\n\x10\x61\x64\x64itionalAmount\x18! \x01(\t\x12\x16\n\x0e\x61\x63tivityAmount\x18\" \x01(\t\"\xa0\x01\n\x0f\x44irectPayResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12(\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x1a.DirectPayResult.SpendData\x1a\x35\n\tSpendData\x12\x14\n\x0cpayRequestId\x18\x01 \x02(\t\x12\x12\n\nsettleDate\x18\x02 \x02(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,Product_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIRECTPAYREQUEST = _descriptor.Descriptor(
  name='DirectPayRequest',
  full_name='DirectPayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='DirectPayRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerOrder', full_name='DirectPayRequest.partnerOrder', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerId', full_name='DirectPayRequest.partnerId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='DirectPayRequest.country', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='DirectPayRequest.payType', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='DirectPayRequest.channel', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payAmount', full_name='DirectPayRequest.payAmount', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='DirectPayRequest.currency', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isCocoinRechargeAndSpend', full_name='DirectPayRequest.isCocoinRechargeAndSpend', index=8,
      number=9, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='DirectPayRequest.product', index=9,
      number=11, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notifyUrl', full_name='DirectPayRequest.notifyUrl', index=10,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerParams', full_name='DirectPayRequest.partnerParams', index=11,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extendParams', full_name='DirectPayRequest.extendParams', index=12,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponId', full_name='DirectPayRequest.couponId', index=13,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discountAmount', full_name='DirectPayRequest.discountAmount', index=14,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pointCardNo', full_name='DirectPayRequest.pointCardNo', index=15,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pointCardPassword', full_name='DirectPayRequest.pointCardPassword', index=16,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hasAdditionalFees', full_name='DirectPayRequest.hasAdditionalFees', index=17,
      number=27, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factor', full_name='DirectPayRequest.factor', index=18,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payActivityId', full_name='DirectPayRequest.payActivityId', index=19,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='additionalAmount', full_name='DirectPayRequest.additionalAmount', index=20,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activityAmount', full_name='DirectPayRequest.activityAmount', index=21,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=566,
)


_DIRECTPAYRESULT_SPENDDATA = _descriptor.Descriptor(
  name='SpendData',
  full_name='DirectPayResult.SpendData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payRequestId', full_name='DirectPayResult.SpendData.payRequestId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settleDate', full_name='DirectPayResult.SpendData.settleDate', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=676,
  serialized_end=729,
)

_DIRECTPAYRESULT = _descriptor.Descriptor(
  name='DirectPayResult',
  full_name='DirectPayResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='DirectPayResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='DirectPayResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='DirectPayResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='DirectPayResult.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DIRECTPAYRESULT_SPENDDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=729,
)

_DIRECTPAYREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_DIRECTPAYREQUEST.fields_by_name['product'].message_type = Product_pb2._PRODUCT
_DIRECTPAYRESULT_SPENDDATA.containing_type = _DIRECTPAYRESULT
_DIRECTPAYRESULT.fields_by_name['data'].message_type = _DIRECTPAYRESULT_SPENDDATA
DESCRIPTOR.message_types_by_name['DirectPayRequest'] = _DIRECTPAYREQUEST
DESCRIPTOR.message_types_by_name['DirectPayResult'] = _DIRECTPAYRESULT

DirectPayRequest = _reflection.GeneratedProtocolMessageType('DirectPayRequest', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTPAYREQUEST,
  __module__ = 'DirectPay_pb2'
  # @@protoc_insertion_point(class_scope:DirectPayRequest)
  ))
_sym_db.RegisterMessage(DirectPayRequest)

DirectPayResult = _reflection.GeneratedProtocolMessageType('DirectPayResult', (_message.Message,), dict(

  SpendData = _reflection.GeneratedProtocolMessageType('SpendData', (_message.Message,), dict(
    DESCRIPTOR = _DIRECTPAYRESULT_SPENDDATA,
    __module__ = 'DirectPay_pb2'
    # @@protoc_insertion_point(class_scope:DirectPayResult.SpendData)
    ))
  ,
  DESCRIPTOR = _DIRECTPAYRESULT,
  __module__ = 'DirectPay_pb2'
  # @@protoc_insertion_point(class_scope:DirectPayResult)
  ))
_sym_db.RegisterMessage(DirectPayResult)
_sym_db.RegisterMessage(DirectPayResult.SpendData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
