# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityActive.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb_src.python_standard import BaseHeaderOut_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ActivityActive.proto',
  package='',
  serialized_pb=_b('\n\x14\x41\x63tivityActive.proto\x1a\x13\x42\x61seHeaderOut.proto\"\xa8\x01\n\x15\x41\x63tivityActiveRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12>\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x30.ActivityActiveRequest.ActivityActiveRequestData\x1a/\n\x19\x41\x63tivityActiveRequestData\x12\x12\n\nactivityId\x18\x01 \x02(\t\"\x87\x02\n\x14\x41\x63tivityActiveResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12<\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32..ActivityActiveResult.ActivityActiveResultData\x1a\x82\x01\n\x18\x41\x63tivityActiveResultData\x12\x12\n\nactivityId\x18\x01 \x02(\t\x12\x14\n\x0c\x61\x63tivityType\x18\x02 \x02(\t\x12\x16\n\x0e\x61\x63tivityStatus\x18\x03 \x02(\t\x12\x14\n\x0cpromtMessage\x18\x04 \x01(\t\x12\x0e\n\x06userId\x18\x05 \x01(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTIVITYACTIVEREQUEST_ACTIVITYACTIVEREQUESTDATA = _descriptor.Descriptor(
  name='ActivityActiveRequestData',
  full_name='ActivityActiveRequest.ActivityActiveRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='ActivityActiveRequest.ActivityActiveRequestData.activityId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=214,
)

_ACTIVITYACTIVEREQUEST = _descriptor.Descriptor(
  name='ActivityActiveRequest',
  full_name='ActivityActiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ActivityActiveRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ActivityActiveRequest.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTIVITYACTIVEREQUEST_ACTIVITYACTIVEREQUESTDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=214,
)


_ACTIVITYACTIVERESULT_ACTIVITYACTIVERESULTDATA = _descriptor.Descriptor(
  name='ActivityActiveResultData',
  full_name='ActivityActiveResult.ActivityActiveResultData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='ActivityActiveResult.ActivityActiveResultData.activityId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activityType', full_name='ActivityActiveResult.ActivityActiveResultData.activityType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activityStatus', full_name='ActivityActiveResult.ActivityActiveResultData.activityStatus', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='promtMessage', full_name='ActivityActiveResult.ActivityActiveResultData.promtMessage', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userId', full_name='ActivityActiveResult.ActivityActiveResultData.userId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=480,
)

_ACTIVITYACTIVERESULT = _descriptor.Descriptor(
  name='ActivityActiveResult',
  full_name='ActivityActiveResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='ActivityActiveResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='ActivityActiveResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='ActivityActiveResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ActivityActiveResult.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTIVITYACTIVERESULT_ACTIVITYACTIVERESULTDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=480,
)

_ACTIVITYACTIVEREQUEST_ACTIVITYACTIVEREQUESTDATA.containing_type = _ACTIVITYACTIVEREQUEST
_ACTIVITYACTIVEREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_ACTIVITYACTIVEREQUEST.fields_by_name['data'].message_type = _ACTIVITYACTIVEREQUEST_ACTIVITYACTIVEREQUESTDATA
_ACTIVITYACTIVERESULT_ACTIVITYACTIVERESULTDATA.containing_type = _ACTIVITYACTIVERESULT
_ACTIVITYACTIVERESULT.fields_by_name['data'].message_type = _ACTIVITYACTIVERESULT_ACTIVITYACTIVERESULTDATA
DESCRIPTOR.message_types_by_name['ActivityActiveRequest'] = _ACTIVITYACTIVEREQUEST
DESCRIPTOR.message_types_by_name['ActivityActiveResult'] = _ACTIVITYACTIVERESULT

ActivityActiveRequest = _reflection.GeneratedProtocolMessageType('ActivityActiveRequest', (_message.Message,), dict(

  ActivityActiveRequestData = _reflection.GeneratedProtocolMessageType('ActivityActiveRequestData', (_message.Message,), dict(
    DESCRIPTOR = _ACTIVITYACTIVEREQUEST_ACTIVITYACTIVEREQUESTDATA,
    __module__ = 'ActivityActive_pb2'
    # @@protoc_insertion_point(class_scope:ActivityActiveRequest.ActivityActiveRequestData)
    ))
  ,
  DESCRIPTOR = _ACTIVITYACTIVEREQUEST,
  __module__ = 'ActivityActive_pb2'
  # @@protoc_insertion_point(class_scope:ActivityActiveRequest)
  ))
_sym_db.RegisterMessage(ActivityActiveRequest)
_sym_db.RegisterMessage(ActivityActiveRequest.ActivityActiveRequestData)

ActivityActiveResult = _reflection.GeneratedProtocolMessageType('ActivityActiveResult', (_message.Message,), dict(

  ActivityActiveResultData = _reflection.GeneratedProtocolMessageType('ActivityActiveResultData', (_message.Message,), dict(
    DESCRIPTOR = _ACTIVITYACTIVERESULT_ACTIVITYACTIVERESULTDATA,
    __module__ = 'ActivityActive_pb2'
    # @@protoc_insertion_point(class_scope:ActivityActiveResult.ActivityActiveResultData)
    ))
  ,
  DESCRIPTOR = _ACTIVITYACTIVERESULT,
  __module__ = 'ActivityActive_pb2'
  # @@protoc_insertion_point(class_scope:ActivityActiveResult)
  ))
_sym_db.RegisterMessage(ActivityActiveResult)
_sym_db.RegisterMessage(ActivityActiveResult.ActivityActiveResultData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
