# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BankCardInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb_src.python_standard import BaseHeaderOut_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BankCardInfo.proto',
  package='',
  serialized_pb=_b('\n\x12\x42\x61nkCardInfo.proto\x1a\x13\x42\x61seHeaderOut.proto\"y\n\x13\x42\x61nkCardInfoRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x13\n\x0b\x61greementNo\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\"\x9b\x02\n\x14\x42\x61nkCardInfoResponse\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12<\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32..BankCardInfoResponse.BankCardInfoResponseData\x1a\x96\x01\n\x18\x42\x61nkCardInfoResponseData\x12\n\n\x02id\x18\x01 \x02(\t\x12\x13\n\x0b\x61greementNo\x18\x02 \x02(\t\x12\x12\n\npictureUrl\x18\x03 \x01(\t\x12\x0f\n\x07payType\x18\x04 \x02(\t\x12\x10\n\x08\x62\x61nkName\x18\x05 \x02(\t\x12\x0e\n\x06\x63\x61rdNo\x18\x06 \x02(\t\x12\x12\n\nbackColour\x18\x07 \x01(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BANKCARDINFOREQUEST = _descriptor.Descriptor(
  name='BankCardInfoRequest',
  full_name='BankCardInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='BankCardInfoRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='agreementNo', full_name='BankCardInfoRequest.agreementNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='BankCardInfoRequest.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='BankCardInfoRequest.country', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='BankCardInfoRequest.currency', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=164,
)


_BANKCARDINFORESPONSE_BANKCARDINFORESPONSEDATA = _descriptor.Descriptor(
  name='BankCardInfoResponseData',
  full_name='BankCardInfoResponse.BankCardInfoResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BankCardInfoResponse.BankCardInfoResponseData.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='agreementNo', full_name='BankCardInfoResponse.BankCardInfoResponseData.agreementNo', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pictureUrl', full_name='BankCardInfoResponse.BankCardInfoResponseData.pictureUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='BankCardInfoResponse.BankCardInfoResponseData.payType', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bankName', full_name='BankCardInfoResponse.BankCardInfoResponseData.bankName', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cardNo', full_name='BankCardInfoResponse.BankCardInfoResponseData.cardNo', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backColour', full_name='BankCardInfoResponse.BankCardInfoResponseData.backColour', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=450,
)

_BANKCARDINFORESPONSE = _descriptor.Descriptor(
  name='BankCardInfoResponse',
  full_name='BankCardInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='BankCardInfoResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='BankCardInfoResponse.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='BankCardInfoResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='BankCardInfoResponse.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BANKCARDINFORESPONSE_BANKCARDINFORESPONSEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=450,
)

_BANKCARDINFOREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_BANKCARDINFORESPONSE_BANKCARDINFORESPONSEDATA.containing_type = _BANKCARDINFORESPONSE
_BANKCARDINFORESPONSE.fields_by_name['data'].message_type = _BANKCARDINFORESPONSE_BANKCARDINFORESPONSEDATA
DESCRIPTOR.message_types_by_name['BankCardInfoRequest'] = _BANKCARDINFOREQUEST
DESCRIPTOR.message_types_by_name['BankCardInfoResponse'] = _BANKCARDINFORESPONSE

BankCardInfoRequest = _reflection.GeneratedProtocolMessageType('BankCardInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _BANKCARDINFOREQUEST,
  __module__ = 'BankCardInfo_pb2'
  # @@protoc_insertion_point(class_scope:BankCardInfoRequest)
  ))
_sym_db.RegisterMessage(BankCardInfoRequest)

BankCardInfoResponse = _reflection.GeneratedProtocolMessageType('BankCardInfoResponse', (_message.Message,), dict(

  BankCardInfoResponseData = _reflection.GeneratedProtocolMessageType('BankCardInfoResponseData', (_message.Message,), dict(
    DESCRIPTOR = _BANKCARDINFORESPONSE_BANKCARDINFORESPONSEDATA,
    __module__ = 'BankCardInfo_pb2'
    # @@protoc_insertion_point(class_scope:BankCardInfoResponse.BankCardInfoResponseData)
    ))
  ,
  DESCRIPTOR = _BANKCARDINFORESPONSE,
  __module__ = 'BankCardInfo_pb2'
  # @@protoc_insertion_point(class_scope:BankCardInfoResponse)
  ))
_sym_db.RegisterMessage(BankCardInfoResponse)
_sym_db.RegisterMessage(BankCardInfoResponse.BankCardInfoResponseData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
