# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BaseHeaderOut.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BaseHeaderOut.proto',
  package='',
  serialized_pb=_b('\n\x13\x42\x61seHeaderOut.proto\"\xab\x02\n\rBaseHeaderOut\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0c\n\x04imei\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0f\n\x07\x61pntype\x18\x05 \x01(\t\x12\x0f\n\x07package\x18\x06 \x01(\t\x12\x0b\n\x03r_v\x18\x07 \x02(\t\x12\x0c\n\x04sign\x18\x08 \x02(\t\x12\x0e\n\x06sdkVer\x18\t \x01(\t\x12\x12\n\nappVerison\x18\n \x01(\t\x12\n\n\x02ip\x18\x0b \x01(\t\x12\x0e\n\x06openId\x18\x0c \x01(\t\x12\x11\n\tbrandType\x18\r \x01(\t\x12\x11\n\tosVersion\x18\x0e \x01(\t\x12\x10\n\x08mobileos\x18\x0f \x01(\t\x12\x16\n\x0e\x61ndroidVersion\x18\x10 \x01(\t\x12\x10\n\x08platform\x18\x11 \x01(\tB\x13\n\x11\x63om.oppo.pay.bean')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BASEHEADEROUT = _descriptor.Descriptor(
  name='BaseHeaderOut',
  full_name='BaseHeaderOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='BaseHeaderOut.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='BaseHeaderOut.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imei', full_name='BaseHeaderOut.imei', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='BaseHeaderOut.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apntype', full_name='BaseHeaderOut.apntype', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='package', full_name='BaseHeaderOut.package', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r_v', full_name='BaseHeaderOut.r_v', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sign', full_name='BaseHeaderOut.sign', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdkVer', full_name='BaseHeaderOut.sdkVer', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appVerison', full_name='BaseHeaderOut.appVerison', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='BaseHeaderOut.ip', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openId', full_name='BaseHeaderOut.openId', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brandType', full_name='BaseHeaderOut.brandType', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='osVersion', full_name='BaseHeaderOut.osVersion', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobileos', full_name='BaseHeaderOut.mobileos', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='androidVersion', full_name='BaseHeaderOut.androidVersion', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform', full_name='BaseHeaderOut.platform', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['BaseHeaderOut'] = _BASEHEADEROUT

BaseHeaderOut = _reflection.GeneratedProtocolMessageType('BaseHeaderOut', (_message.Message,), dict(
  DESCRIPTOR = _BASEHEADEROUT,
  __module__ = 'BaseHeaderOut_pb2'
  # @@protoc_insertion_point(class_scope:BaseHeaderOut)
  ))
_sym_db.RegisterMessage(BaseHeaderOut)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
