# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CouponInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BaseHeaderOut_pb2
from . import Exchange_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CouponInfo.proto',
  package='',
  serialized_pb=_b('\n\x10\x43ouponInfo.proto\x1a\x13\x42\x61seHeaderOut.proto\"y\n\x11\x43ouponInfoRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x11\n\tpartnerId\x18\x02 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x02(\t\x12\x10\n\x08\x63urrency\x18\x04 \x02(\t\x12\x0e\n\x06\x66\x61\x63tor\x18\x05 \x01(\t\"\xdd\x02\n\x12\x43ouponInfoResponse\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x38\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32*.CouponInfoResponse.CouponInfoResponseData\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x1a\xcc\x01\n\x16\x43ouponInfoResponseData\x12\x10\n\x08\x63ouponId\x18\x01 \x02(\t\x12\x12\n\ncouponType\x18\x02 \x02(\t\x12\x13\n\x0b\x63ouponValue\x18\x03 \x02(\t\x12\x12\n\nminCousume\x18\x04 \x02(\t\x12\x13\n\x0b\x63ouponRatio\x18\x05 \x02(\t\x12\x13\n\x0bmaxDiscount\x18\x06 \x02(\t\x12\x11\n\tusableAmt\x18\x07 \x02(\t\x12\x0e\n\x06status\x18\x08 \x02(\t\x12\x16\n\x0euseableEndTime\x18\t \x02(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COUPONINFOREQUEST = _descriptor.Descriptor(
  name='CouponInfoRequest',
  full_name='CouponInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='CouponInfoRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerId', full_name='CouponInfoRequest.partnerId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='CouponInfoRequest.country', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='CouponInfoRequest.currency', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factor', full_name='CouponInfoRequest.factor', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=162,
)


_COUPONINFORESPONSE_COUPONINFORESPONSEDATA = _descriptor.Descriptor(
  name='CouponInfoResponseData',
  full_name='CouponInfoResponse.CouponInfoResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='couponId', full_name='CouponInfoResponse.CouponInfoResponseData.couponId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponType', full_name='CouponInfoResponse.CouponInfoResponseData.couponType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponValue', full_name='CouponInfoResponse.CouponInfoResponseData.couponValue', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minCousume', full_name='CouponInfoResponse.CouponInfoResponseData.minCousume', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponRatio', full_name='CouponInfoResponse.CouponInfoResponseData.couponRatio', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxDiscount', full_name='CouponInfoResponse.CouponInfoResponseData.maxDiscount', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usableAmt', full_name='CouponInfoResponse.CouponInfoResponseData.usableAmt', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='CouponInfoResponse.CouponInfoResponseData.status', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='useableEndTime', full_name='CouponInfoResponse.CouponInfoResponseData.useableEndTime', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=514,
)

_COUPONINFORESPONSE = _descriptor.Descriptor(
  name='CouponInfoResponse',
  full_name='CouponInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='CouponInfoResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='CouponInfoResponse.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='CouponInfoResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='CouponInfoResponse.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='CouponInfoResponse.currency', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COUPONINFORESPONSE_COUPONINFORESPONSEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=514,
)

_COUPONINFOREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_COUPONINFORESPONSE_COUPONINFORESPONSEDATA.containing_type = _COUPONINFORESPONSE
_COUPONINFORESPONSE.fields_by_name['data'].message_type = _COUPONINFORESPONSE_COUPONINFORESPONSEDATA
DESCRIPTOR.message_types_by_name['CouponInfoRequest'] = _COUPONINFOREQUEST
DESCRIPTOR.message_types_by_name['CouponInfoResponse'] = _COUPONINFORESPONSE

CouponInfoRequest = _reflection.GeneratedProtocolMessageType('CouponInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _COUPONINFOREQUEST,
  __module__ = 'CouponInfo_pb2'
  # @@protoc_insertion_point(class_scope:CouponInfoRequest)
  ))
_sym_db.RegisterMessage(CouponInfoRequest)

CouponInfoResponse = _reflection.GeneratedProtocolMessageType('CouponInfoResponse', (_message.Message,), dict(

  CouponInfoResponseData = _reflection.GeneratedProtocolMessageType('CouponInfoResponseData', (_message.Message,), dict(
    DESCRIPTOR = _COUPONINFORESPONSE_COUPONINFORESPONSEDATA,
    __module__ = 'CouponInfo_pb2'
    # @@protoc_insertion_point(class_scope:CouponInfoResponse.CouponInfoResponseData)
    ))
  ,
  DESCRIPTOR = _COUPONINFORESPONSE,
  __module__ = 'CouponInfo_pb2'
  # @@protoc_insertion_point(class_scope:CouponInfoResponse)
  ))
_sym_db.RegisterMessage(CouponInfoResponse)
_sym_db.RegisterMessage(CouponInfoResponse.CouponInfoResponseData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
