# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Exchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.pb_src.python_standard import BaseHeaderOut_pb2
from lib.pb_src.python_standard import Product_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Exchange.proto',
  package='',
  serialized_pb=_b('\n\x0e\x45xchange.proto\x1a\x13\x42\x61seHeaderOut.proto\"\xa2\x01\n\x0f\x45xchangeRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x32\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32$.ExchangeRequest.ExchangeRequestData\x1a;\n\x13\x45xchangeRequestData\x12\x0f\n\x07\x63ountry\x18\x01 \x02(\t\x12\x13\n\x0bsrcCurrency\x18\x02 \x02(\t\"\xe7\x01\n\x0e\x45xchangeResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x30\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\".ExchangeResult.ExchangeResultData\x1au\n\x12\x45xchangeResultData\x12\x0f\n\x07\x63ountry\x18\x01 \x02(\t\x12\x13\n\x0bsrcCurrency\x18\x02 \x02(\t\x12\x13\n\x0b\x64stCurrency\x18\x03 \x02(\t\x12\x11\n\tsrcAmount\x18\x04 \x02(\t\x12\x11\n\tdstAmount\x18\x05 \x02(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXCHANGEREQUEST_EXCHANGEREQUESTDATA = _descriptor.Descriptor(
  name='ExchangeRequestData',
  full_name='ExchangeRequest.ExchangeRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='ExchangeRequest.ExchangeRequestData.country', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srcCurrency', full_name='ExchangeRequest.ExchangeRequestData.srcCurrency', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=202,
)

_EXCHANGEREQUEST = _descriptor.Descriptor(
  name='ExchangeRequest',
  full_name='ExchangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ExchangeRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ExchangeRequest.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXCHANGEREQUEST_EXCHANGEREQUESTDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=202,
)


_EXCHANGERESULT_EXCHANGERESULTDATA = _descriptor.Descriptor(
  name='ExchangeResultData',
  full_name='ExchangeResult.ExchangeResultData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='ExchangeResult.ExchangeResultData.country', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srcCurrency', full_name='ExchangeResult.ExchangeResultData.srcCurrency', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dstCurrency', full_name='ExchangeResult.ExchangeResultData.dstCurrency', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srcAmount', full_name='ExchangeResult.ExchangeResultData.srcAmount', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dstAmount', full_name='ExchangeResult.ExchangeResultData.dstAmount', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=436,
)

_EXCHANGERESULT = _descriptor.Descriptor(
  name='ExchangeResult',
  full_name='ExchangeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='ExchangeResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='ExchangeResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='ExchangeResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ExchangeResult.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXCHANGERESULT_EXCHANGERESULTDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=436,
)

_EXCHANGEREQUEST_EXCHANGEREQUESTDATA.containing_type = _EXCHANGEREQUEST
_EXCHANGEREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_EXCHANGEREQUEST.fields_by_name['data'].message_type = _EXCHANGEREQUEST_EXCHANGEREQUESTDATA
_EXCHANGERESULT_EXCHANGERESULTDATA.containing_type = _EXCHANGERESULT
_EXCHANGERESULT.fields_by_name['data'].message_type = _EXCHANGERESULT_EXCHANGERESULTDATA
DESCRIPTOR.message_types_by_name['ExchangeRequest'] = _EXCHANGEREQUEST
DESCRIPTOR.message_types_by_name['ExchangeResult'] = _EXCHANGERESULT

ExchangeRequest = _reflection.GeneratedProtocolMessageType('ExchangeRequest', (_message.Message,), dict(

  ExchangeRequestData = _reflection.GeneratedProtocolMessageType('ExchangeRequestData', (_message.Message,), dict(
    DESCRIPTOR = _EXCHANGEREQUEST_EXCHANGEREQUESTDATA,
    __module__ = 'Exchange_pb2'
    # @@protoc_insertion_point(class_scope:ExchangeRequest.ExchangeRequestData)
    ))
  ,
  DESCRIPTOR = _EXCHANGEREQUEST,
  __module__ = 'Exchange_pb2'
  # @@protoc_insertion_point(class_scope:ExchangeRequest)
  ))
_sym_db.RegisterMessage(ExchangeRequest)
_sym_db.RegisterMessage(ExchangeRequest.ExchangeRequestData)

ExchangeResult = _reflection.GeneratedProtocolMessageType('ExchangeResult', (_message.Message,), dict(

  ExchangeResultData = _reflection.GeneratedProtocolMessageType('ExchangeResultData', (_message.Message,), dict(
    DESCRIPTOR = _EXCHANGERESULT_EXCHANGERESULTDATA,
    __module__ = 'Exchange_pb2'
    # @@protoc_insertion_point(class_scope:ExchangeResult.ExchangeResultData)
    ))
  ,
  DESCRIPTOR = _EXCHANGERESULT,
  __module__ = 'Exchange_pb2'
  # @@protoc_insertion_point(class_scope:ExchangeResult)
  ))
_sym_db.RegisterMessage(ExchangeResult)
_sym_db.RegisterMessage(ExchangeResult.ExchangeResultData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
