# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MobileModelReport.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BaseHeaderOut_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MobileModelReport.proto',
  package='',
  serialized_pb=_b('\n\x17MobileModelReport.proto\x1a\x13\x42\x61seHeaderOut.proto\"K\n\x18MobileModelReportRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"G\n\x17MobileModelReportResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOBILEMODELREPORTREQUEST = _descriptor.Descriptor(
  name='MobileModelReportRequest',
  full_name='MobileModelReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='MobileModelReportRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='MobileModelReportRequest.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=123,
)


_MOBILEMODELREPORTRESULT = _descriptor.Descriptor(
  name='MobileModelReportResult',
  full_name='MobileModelReportResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='MobileModelReportResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='MobileModelReportResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='MobileModelReportResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=196,
)

_MOBILEMODELREPORTREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
DESCRIPTOR.message_types_by_name['MobileModelReportRequest'] = _MOBILEMODELREPORTREQUEST
DESCRIPTOR.message_types_by_name['MobileModelReportResult'] = _MOBILEMODELREPORTRESULT

MobileModelReportRequest = _reflection.GeneratedProtocolMessageType('MobileModelReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOBILEMODELREPORTREQUEST,
  __module__ = 'MobileModelReport_pb2'
  # @@protoc_insertion_point(class_scope:MobileModelReportRequest)
  ))
_sym_db.RegisterMessage(MobileModelReportRequest)

MobileModelReportResult = _reflection.GeneratedProtocolMessageType('MobileModelReportResult', (_message.Message,), dict(
  DESCRIPTOR = _MOBILEMODELREPORTRESULT,
  __module__ = 'MobileModelReport_pb2'
  # @@protoc_insertion_point(class_scope:MobileModelReportResult)
  ))
_sym_db.RegisterMessage(MobileModelReportResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
