# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MomoUpOrderPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BaseHeaderOut_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MomoUpOrderPb.proto',
  package='',
  serialized_pb=_b('\n\x13MomoUpOrderPb.proto\x1a\x13\x42\x61seHeaderOut.proto\"\xd4\x01\n\x12MomoUpOrderRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x0f\n\x07orderId\x18\x02 \x02(\t\x12\x16\n\x0e\x63ustomerNumber\x18\x03 \x01(\t\x12\x0f\n\x07\x61ppData\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0f\n\x07payType\x18\x07 \x01(\t\x12\x16\n\x0etelkomselToken\x18\x08 \x01(\t\x12\x16\n\x0etelkomselTrxid\x18\t \x01(\t\"C\n\x13MomoUpOrderResponse\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOMOUPORDERREQUEST = _descriptor.Descriptor(
  name='MomoUpOrderRequest',
  full_name='MomoUpOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='MomoUpOrderRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderId', full_name='MomoUpOrderRequest.orderId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='customerNumber', full_name='MomoUpOrderRequest.customerNumber', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appData', full_name='MomoUpOrderRequest.appData', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='MomoUpOrderRequest.amount', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='MomoUpOrderRequest.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='MomoUpOrderRequest.payType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telkomselToken', full_name='MomoUpOrderRequest.telkomselToken', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telkomselTrxid', full_name='MomoUpOrderRequest.telkomselTrxid', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=257,
)


_MOMOUPORDERRESPONSE = _descriptor.Descriptor(
  name='MomoUpOrderResponse',
  full_name='MomoUpOrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='MomoUpOrderResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='MomoUpOrderResponse.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='MomoUpOrderResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=326,
)

_MOMOUPORDERREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
DESCRIPTOR.message_types_by_name['MomoUpOrderRequest'] = _MOMOUPORDERREQUEST
DESCRIPTOR.message_types_by_name['MomoUpOrderResponse'] = _MOMOUPORDERRESPONSE

MomoUpOrderRequest = _reflection.GeneratedProtocolMessageType('MomoUpOrderRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOMOUPORDERREQUEST,
  __module__ = 'MomoUpOrderPb_pb2'
  # @@protoc_insertion_point(class_scope:MomoUpOrderRequest)
  ))
_sym_db.RegisterMessage(MomoUpOrderRequest)

MomoUpOrderResponse = _reflection.GeneratedProtocolMessageType('MomoUpOrderResponse', (_message.Message,), dict(
  DESCRIPTOR = _MOMOUPORDERRESPONSE,
  __module__ = 'MomoUpOrderPb_pb2'
  # @@protoc_insertion_point(class_scope:MomoUpOrderResponse)
  ))
_sym_db.RegisterMessage(MomoUpOrderResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
