# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PayQuery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.pb_src.python_standard import BaseHeaderOut_pb2
from lib.pb_src.python_standard import Product_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PayQuery.proto',
  package='',
  serialized_pb=_b('\n\x0ePayQuery.proto\x1a\x13\x42\x61seHeaderOut.proto\x1a\rProduct.proto\"k\n\x0fPayQueryRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x14\n\x0cpayRequestId\x18\x02 \x02(\t\x12\x11\n\ttradeType\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\"\x81\x05\n\x10PayQueryResponse\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x34\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32&.PayQueryResponse.PayTokenResponseData\x1a\x88\x04\n\x14PayTokenResponseData\x12\x14\n\x0cpayRequestId\x18\x01 \x02(\t\x12\x14\n\x0cpartnerOrder\x18\x02 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0f\n\x07payType\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\x12\x11\n\tpayAmount\x18\x06 \x02(\t\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x02(\t\x12\x12\n\nsettleDate\x18\t \x01(\t\x12\x19\n\x07product\x18\n \x01(\x0b\x32\x08.Product\x12\x41\n\raddtionalFees\x18\x0b \x03(\x0b\x32*.PayQueryResponse.PayTokenResponseData.Fee\x12\x14\n\x0c\x62usinessType\x18\x10 \x01(\t\x12\x19\n\x11\x61\x64\x64itionFeeAmount\x18\x11 \x01(\t\x12\x1c\n\x14\x63ocoinRechargeAmount\x18\x12 \x01(\t\x12\x19\n\x11\x63ocoinSpendAmount\x18\x13 \x01(\t\x12\x14\n\x0c\x63ouponAmount\x18\x14 \x01(\t\x12\x19\n\x11payDiscountAmount\x18\x15 \x01(\t\x12\x18\n\x10\x63ocoinGiftAmount\x18\x16 \x01(\t\x1a\x35\n\x03\x46\x65\x65\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06\x61mount\x18\x02 \x02(\t\x12\x10\n\x08\x63urrency\x18\x03 \x02(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,Product_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PAYQUERYREQUEST = _descriptor.Descriptor(
  name='PayQueryRequest',
  full_name='PayQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='PayQueryRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payRequestId', full_name='PayQueryRequest.payRequestId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tradeType', full_name='PayQueryRequest.tradeType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='PayQueryRequest.country', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=161,
)


_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA_FEE = _descriptor.Descriptor(
  name='Fee',
  full_name='PayQueryResponse.PayTokenResponseData.Fee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PayQueryResponse.PayTokenResponseData.Fee.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='PayQueryResponse.PayTokenResponseData.Fee.amount', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='PayQueryResponse.PayTokenResponseData.Fee.currency', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=752,
  serialized_end=805,
)

_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA = _descriptor.Descriptor(
  name='PayTokenResponseData',
  full_name='PayQueryResponse.PayTokenResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payRequestId', full_name='PayQueryResponse.PayTokenResponseData.payRequestId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerOrder', full_name='PayQueryResponse.PayTokenResponseData.partnerOrder', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='PayQueryResponse.PayTokenResponseData.country', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='PayQueryResponse.PayTokenResponseData.payType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='PayQueryResponse.PayTokenResponseData.channel', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payAmount', full_name='PayQueryResponse.PayTokenResponseData.payAmount', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='PayQueryResponse.PayTokenResponseData.currency', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='PayQueryResponse.PayTokenResponseData.status', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settleDate', full_name='PayQueryResponse.PayTokenResponseData.settleDate', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='PayQueryResponse.PayTokenResponseData.product', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addtionalFees', full_name='PayQueryResponse.PayTokenResponseData.addtionalFees', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='businessType', full_name='PayQueryResponse.PayTokenResponseData.businessType', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='additionFeeAmount', full_name='PayQueryResponse.PayTokenResponseData.additionFeeAmount', index=12,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cocoinRechargeAmount', full_name='PayQueryResponse.PayTokenResponseData.cocoinRechargeAmount', index=13,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cocoinSpendAmount', full_name='PayQueryResponse.PayTokenResponseData.cocoinSpendAmount', index=14,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponAmount', full_name='PayQueryResponse.PayTokenResponseData.couponAmount', index=15,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payDiscountAmount', full_name='PayQueryResponse.PayTokenResponseData.payDiscountAmount', index=16,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cocoinGiftAmount', full_name='PayQueryResponse.PayTokenResponseData.cocoinGiftAmount', index=17,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA_FEE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=805,
)

_PAYQUERYRESPONSE = _descriptor.Descriptor(
  name='PayQueryResponse',
  full_name='PayQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='PayQueryResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='PayQueryResponse.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='PayQueryResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='PayQueryResponse.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=805,
)

_PAYQUERYREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA_FEE.containing_type = _PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA
_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA.fields_by_name['product'].message_type = Product_pb2._PRODUCT
_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA.fields_by_name['addtionalFees'].message_type = _PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA_FEE
_PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA.containing_type = _PAYQUERYRESPONSE
_PAYQUERYRESPONSE.fields_by_name['data'].message_type = _PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA
DESCRIPTOR.message_types_by_name['PayQueryRequest'] = _PAYQUERYREQUEST
DESCRIPTOR.message_types_by_name['PayQueryResponse'] = _PAYQUERYRESPONSE

PayQueryRequest = _reflection.GeneratedProtocolMessageType('PayQueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _PAYQUERYREQUEST,
  __module__ = 'PayQuery_pb2'
  # @@protoc_insertion_point(class_scope:PayQueryRequest)
  ))
_sym_db.RegisterMessage(PayQueryRequest)

PayQueryResponse = _reflection.GeneratedProtocolMessageType('PayQueryResponse', (_message.Message,), dict(

  PayTokenResponseData = _reflection.GeneratedProtocolMessageType('PayTokenResponseData', (_message.Message,), dict(

    Fee = _reflection.GeneratedProtocolMessageType('Fee', (_message.Message,), dict(
      DESCRIPTOR = _PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA_FEE,
      __module__ = 'PayQuery_pb2'
      # @@protoc_insertion_point(class_scope:PayQueryResponse.PayTokenResponseData.Fee)
      ))
    ,
    DESCRIPTOR = _PAYQUERYRESPONSE_PAYTOKENRESPONSEDATA,
    __module__ = 'PayQuery_pb2'
    # @@protoc_insertion_point(class_scope:PayQueryResponse.PayTokenResponseData)
    ))
  ,
  DESCRIPTOR = _PAYQUERYRESPONSE,
  __module__ = 'PayQuery_pb2'
  # @@protoc_insertion_point(class_scope:PayQueryResponse)
  ))
_sym_db.RegisterMessage(PayQueryResponse)
_sym_db.RegisterMessage(PayQueryResponse.PayTokenResponseData)
_sym_db.RegisterMessage(PayQueryResponse.PayTokenResponseData.Fee)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
