# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryPackage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BaseHeaderOut_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueryPackage.proto',
  package='',
  serialized_pb=_b('\n\x12QueryPackage.proto\x1a\x13\x42\x61seHeaderOut.proto\"F\n\x13QueryPackageRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"\x83\x01\n\x12QueryPackageResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x15\n\roppoucPackage\x18\x04 \x01(\t\x12\x15\n\rwalletPackage\x18\x05 \x01(\t\x12\x11\n\tucPackage\x18\x06 \x01(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUERYPACKAGEREQUEST = _descriptor.Descriptor(
  name='QueryPackageRequest',
  full_name='QueryPackageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='QueryPackageRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='QueryPackageRequest.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=113,
)


_QUERYPACKAGERESULT = _descriptor.Descriptor(
  name='QueryPackageResult',
  full_name='QueryPackageResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='QueryPackageResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='QueryPackageResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='QueryPackageResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oppoucPackage', full_name='QueryPackageResult.oppoucPackage', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='walletPackage', full_name='QueryPackageResult.walletPackage', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ucPackage', full_name='QueryPackageResult.ucPackage', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=247,
)

_QUERYPACKAGEREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
DESCRIPTOR.message_types_by_name['QueryPackageRequest'] = _QUERYPACKAGEREQUEST
DESCRIPTOR.message_types_by_name['QueryPackageResult'] = _QUERYPACKAGERESULT

QueryPackageRequest = _reflection.GeneratedProtocolMessageType('QueryPackageRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPACKAGEREQUEST,
  __module__ = 'QueryPackage_pb2'
  # @@protoc_insertion_point(class_scope:QueryPackageRequest)
  ))
_sym_db.RegisterMessage(QueryPackageRequest)

QueryPackageResult = _reflection.GeneratedProtocolMessageType('QueryPackageResult', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPACKAGERESULT,
  __module__ = 'QueryPackage_pb2'
  # @@protoc_insertion_point(class_scope:QueryPackageResult)
  ))
_sym_db.RegisterMessage(QueryPackageResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
