# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queryBanner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.pb_src.python_standard import BaseHeaderOut_pb2
from lib.pb_src.python_standard import Product_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='queryBanner.proto',
  package='',
  serialized_pb=_b('\n\x11queryBanner.proto\x1a\x13\x42\x61seHeaderOut.proto\"\x8a\x01\n\x12QueryBannerRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x10\n\x08position\x18\x02 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x11\n\tpartnerId\x18\x04 \x01(\t\x12\x0f\n\x07payType\x18\x05 \x01(\t\x12\r\n\x05\x62izId\x18\x06 \x01(\t\"\xcc\x01\n\x11QueryBannerResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x31\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32#.QueryBannerResult.BannerResultData\x1aV\n\x10\x42\x61nnerResultData\x12\x15\n\rbannerIconUrl\x18\x01 \x02(\t\x12\x15\n\rbannerSkipUrl\x18\x02 \x02(\t\x12\x14\n\x0cshowPosition\x18\x03 \x02(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUERYBANNERREQUEST = _descriptor.Descriptor(
  name='QueryBannerRequest',
  full_name='QueryBannerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='QueryBannerRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='QueryBannerRequest.position', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='QueryBannerRequest.country', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerId', full_name='QueryBannerRequest.partnerId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='QueryBannerRequest.payType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bizId', full_name='QueryBannerRequest.bizId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=181,
)


_QUERYBANNERRESULT_BANNERRESULTDATA = _descriptor.Descriptor(
  name='BannerResultData',
  full_name='QueryBannerResult.BannerResultData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bannerIconUrl', full_name='QueryBannerResult.BannerResultData.bannerIconUrl', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bannerSkipUrl', full_name='QueryBannerResult.BannerResultData.bannerSkipUrl', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='showPosition', full_name='QueryBannerResult.BannerResultData.showPosition', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=388,
)

_QUERYBANNERRESULT = _descriptor.Descriptor(
  name='QueryBannerResult',
  full_name='QueryBannerResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='QueryBannerResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='QueryBannerResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='QueryBannerResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='QueryBannerResult.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_QUERYBANNERRESULT_BANNERRESULTDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=388,
)

_QUERYBANNERREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_QUERYBANNERRESULT_BANNERRESULTDATA.containing_type = _QUERYBANNERRESULT
_QUERYBANNERRESULT.fields_by_name['data'].message_type = _QUERYBANNERRESULT_BANNERRESULTDATA
DESCRIPTOR.message_types_by_name['QueryBannerRequest'] = _QUERYBANNERREQUEST
DESCRIPTOR.message_types_by_name['QueryBannerResult'] = _QUERYBANNERRESULT

QueryBannerRequest = _reflection.GeneratedProtocolMessageType('QueryBannerRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYBANNERREQUEST,
  __module__ = 'queryBanner_pb2'
  # @@protoc_insertion_point(class_scope:QueryBannerRequest)
  ))
_sym_db.RegisterMessage(QueryBannerRequest)

QueryBannerResult = _reflection.GeneratedProtocolMessageType('QueryBannerResult', (_message.Message,), dict(

  BannerResultData = _reflection.GeneratedProtocolMessageType('BannerResultData', (_message.Message,), dict(
    DESCRIPTOR = _QUERYBANNERRESULT_BANNERRESULTDATA,
    __module__ = 'queryBanner_pb2'
    # @@protoc_insertion_point(class_scope:QueryBannerResult.BannerResultData)
    ))
  ,
  DESCRIPTOR = _QUERYBANNERRESULT,
  __module__ = 'queryBanner_pb2'
  # @@protoc_insertion_point(class_scope:QueryBannerResult)
  ))
_sym_db.RegisterMessage(QueryBannerResult)
_sym_db.RegisterMessage(QueryBannerResult.BannerResultData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
