# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queryIdcUrl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BaseHeaderOut_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='queryIdcUrl.proto',
  package='',
  serialized_pb=_b('\n\x11queryIdcUrl.proto\x1a\x13\x42\x61seHeaderOut.proto\"E\n\x12QueryIdcUrlRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x0f\n\x07\x63ountry\x18\x02 \x02(\t\"Q\n\x11QueryIdcUrlResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0e\n\x06idcUrl\x18\x04 \x01(\tB\x1b\n\x19\x63om.greenfactory.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUERYIDCURLREQUEST = _descriptor.Descriptor(
  name='QueryIdcUrlRequest',
  full_name='QueryIdcUrlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='QueryIdcUrlRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='QueryIdcUrlRequest.country', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=111,
)


_QUERYIDCURLRESULT = _descriptor.Descriptor(
  name='QueryIdcUrlResult',
  full_name='QueryIdcUrlResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='QueryIdcUrlResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='QueryIdcUrlResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='QueryIdcUrlResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idcUrl', full_name='QueryIdcUrlResult.idcUrl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=194,
)

_QUERYIDCURLREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
DESCRIPTOR.message_types_by_name['QueryIdcUrlRequest'] = _QUERYIDCURLREQUEST
DESCRIPTOR.message_types_by_name['QueryIdcUrlResult'] = _QUERYIDCURLRESULT

QueryIdcUrlRequest = _reflection.GeneratedProtocolMessageType('QueryIdcUrlRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYIDCURLREQUEST,
  __module__ = 'queryIdcUrl_pb2'
  # @@protoc_insertion_point(class_scope:QueryIdcUrlRequest)
  ))
_sym_db.RegisterMessage(QueryIdcUrlRequest)

QueryIdcUrlResult = _reflection.GeneratedProtocolMessageType('QueryIdcUrlResult', (_message.Message,), dict(
  DESCRIPTOR = _QUERYIDCURLRESULT,
  __module__ = 'queryIdcUrl_pb2'
  # @@protoc_insertion_point(class_scope:QueryIdcUrlResult)
  ))
_sym_db.RegisterMessage(QueryIdcUrlResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.greenfactory.pay.bean'))
# @@protoc_insertion_point(module_scope)
