# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpeakerInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.pb_src.python_standard import BaseHeaderOut_pb2
from lib.pb_src.python_standard import Product_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpeakerInfo.proto',
  package='',
  serialized_pb=_b('\n\x11SpeakerInfo.proto\x1a\x13\x42\x61seHeaderOut.proto\"\x94\x01\n\x12SpeakerInfoRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x0f\n\x07\x63ountry\x18\x02 \x02(\t\x12\x11\n\tosVersion\x18\x03 \x01(\t\x12\x16\n\x0espeakerVersion\x18\x04 \x01(\x05\x12\r\n\x05\x62izId\x18\x05 \x01(\t\x12\x13\n\x0bpartnerCode\x18\x06 \x01(\t\"\xef\x01\n\x11SpeakerInfoResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x16\n\x0espeakerVersion\x18\x07 \x01(\x05\x12,\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x1e.SpeakerInfoResult.SpeakerData\x1a\x66\n\x0bSpeakerData\x12\x0c\n\x04page\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x02(\t\x12\x10\n\x08\x66romTime\x18\x06 \x02(\t\x12\x0e\n\x06toTime\x18\x07 \x02(\t\x12\x16\n\x0espeakerVersion\x18\x08 \x01(\x05\x42\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPEAKERINFOREQUEST = _descriptor.Descriptor(
  name='SpeakerInfoRequest',
  full_name='SpeakerInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SpeakerInfoRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='SpeakerInfoRequest.country', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='osVersion', full_name='SpeakerInfoRequest.osVersion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speakerVersion', full_name='SpeakerInfoRequest.speakerVersion', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bizId', full_name='SpeakerInfoRequest.bizId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerCode', full_name='SpeakerInfoRequest.partnerCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=191,
)


_SPEAKERINFORESULT_SPEAKERDATA = _descriptor.Descriptor(
  name='SpeakerData',
  full_name='SpeakerInfoResult.SpeakerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='SpeakerInfoResult.SpeakerData.page', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='SpeakerInfoResult.SpeakerData.content', index=1,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fromTime', full_name='SpeakerInfoResult.SpeakerData.fromTime', index=2,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toTime', full_name='SpeakerInfoResult.SpeakerData.toTime', index=3,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speakerVersion', full_name='SpeakerInfoResult.SpeakerData.speakerVersion', index=4,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=433,
)

_SPEAKERINFORESULT = _descriptor.Descriptor(
  name='SpeakerInfoResult',
  full_name='SpeakerInfoResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='SpeakerInfoResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='SpeakerInfoResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='SpeakerInfoResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speakerVersion', full_name='SpeakerInfoResult.speakerVersion', index=3,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='SpeakerInfoResult.data', index=4,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SPEAKERINFORESULT_SPEAKERDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=433,
)

_SPEAKERINFOREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_SPEAKERINFORESULT_SPEAKERDATA.containing_type = _SPEAKERINFORESULT
_SPEAKERINFORESULT.fields_by_name['data'].message_type = _SPEAKERINFORESULT_SPEAKERDATA
DESCRIPTOR.message_types_by_name['SpeakerInfoRequest'] = _SPEAKERINFOREQUEST
DESCRIPTOR.message_types_by_name['SpeakerInfoResult'] = _SPEAKERINFORESULT

SpeakerInfoRequest = _reflection.GeneratedProtocolMessageType('SpeakerInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPEAKERINFOREQUEST,
  __module__ = 'SpeakerInfo_pb2'
  # @@protoc_insertion_point(class_scope:SpeakerInfoRequest)
  ))
_sym_db.RegisterMessage(SpeakerInfoRequest)

SpeakerInfoResult = _reflection.GeneratedProtocolMessageType('SpeakerInfoResult', (_message.Message,), dict(

  SpeakerData = _reflection.GeneratedProtocolMessageType('SpeakerData', (_message.Message,), dict(
    DESCRIPTOR = _SPEAKERINFORESULT_SPEAKERDATA,
    __module__ = 'SpeakerInfo_pb2'
    # @@protoc_insertion_point(class_scope:SpeakerInfoResult.SpeakerData)
    ))
  ,
  DESCRIPTOR = _SPEAKERINFORESULT,
  __module__ = 'SpeakerInfo_pb2'
  # @@protoc_insertion_point(class_scope:SpeakerInfoResult)
  ))
_sym_db.RegisterMessage(SpeakerInfoResult)
_sym_db.RegisterMessage(SpeakerInfoResult.SpeakerData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
