# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Spend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.pb_src.python_standard import BaseHeaderOut_pb2
from lib.pb_src.python_standard import Product_pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Spend.proto',
  package='',
  serialized_pb=_b('\n\x0bSpend.proto\x1a\x13\x42\x61seHeaderOut.proto\x1a\rProduct.proto\"\xb7\x03\n\x0cSpendRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x14\n\x0cpartnerOrder\x18\x02 \x02(\t\x12\x11\n\tpartnerId\x18\x03 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x02(\t\x12\x0f\n\x07payType\x18\x05 \x02(\t\x12\x0f\n\x07\x63hannel\x18\x06 \x02(\t\x12\x11\n\tpayAmount\x18\x07 \x02(\t\x12\x10\n\x08\x63urrency\x18\x08 \x02(\t\x12\x19\n\x07product\x18\x0b \x02(\x0b\x32\x08.Product\x12\x11\n\treturnUrl\x18\x0c \x01(\t\x12\x11\n\tnotifyUrl\x18\r \x01(\t\x12\x15\n\rpartnerParams\x18\x0e \x01(\t\x12\x14\n\x0c\x65xtendParams\x18\x0f \x01(\t\x12\x14\n\x0c\x62usinessType\x18\x10 \x01(\t\x12\x19\n\x11\x62usinessChannelId\x18\x11 \x01(\t\x12\x10\n\x08\x63ouponId\x18\x15 \x01(\t\x12\x16\n\x0e\x64iscountAmount\x18\x16 \x01(\t\x12\x0e\n\x06\x66\x61\x63tor\x18\x1c \x01(\t\x12\x15\n\rpayActivityId\x18\x1d \x01(\t\x12\x16\n\x0e\x61\x63tivityAmount\x18\" \x01(\t\"\x98\x01\n\x0bSpendResult\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12$\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x16.SpendResult.SpendData\x1a\x35\n\tSpendData\x12\x14\n\x0cpayRequestId\x18\x01 \x02(\t\x12\x12\n\nsettleDate\x18\x02 \x02(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,Product_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPENDREQUEST = _descriptor.Descriptor(
  name='SpendRequest',
  full_name='SpendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SpendRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerOrder', full_name='SpendRequest.partnerOrder', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerId', full_name='SpendRequest.partnerId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='SpendRequest.country', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='SpendRequest.payType', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='SpendRequest.channel', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payAmount', full_name='SpendRequest.payAmount', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='SpendRequest.currency', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='SpendRequest.product', index=8,
      number=11, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='returnUrl', full_name='SpendRequest.returnUrl', index=9,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notifyUrl', full_name='SpendRequest.notifyUrl', index=10,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerParams', full_name='SpendRequest.partnerParams', index=11,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extendParams', full_name='SpendRequest.extendParams', index=12,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='businessType', full_name='SpendRequest.businessType', index=13,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='businessChannelId', full_name='SpendRequest.businessChannelId', index=14,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponId', full_name='SpendRequest.couponId', index=15,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discountAmount', full_name='SpendRequest.discountAmount', index=16,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factor', full_name='SpendRequest.factor', index=17,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payActivityId', full_name='SpendRequest.payActivityId', index=18,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activityAmount', full_name='SpendRequest.activityAmount', index=19,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=491,
)


_SPENDRESULT_SPENDDATA = _descriptor.Descriptor(
  name='SpendData',
  full_name='SpendResult.SpendData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payRequestId', full_name='SpendResult.SpendData.payRequestId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settleDate', full_name='SpendResult.SpendData.settleDate', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=646,
)

_SPENDRESULT = _descriptor.Descriptor(
  name='SpendResult',
  full_name='SpendResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='SpendResult.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='SpendResult.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='SpendResult.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='SpendResult.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SPENDRESULT_SPENDDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=646,
)

_SPENDREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_SPENDREQUEST.fields_by_name['product'].message_type = Product_pb2._PRODUCT
_SPENDRESULT_SPENDDATA.containing_type = _SPENDRESULT
_SPENDRESULT.fields_by_name['data'].message_type = _SPENDRESULT_SPENDDATA
DESCRIPTOR.message_types_by_name['SpendRequest'] = _SPENDREQUEST
DESCRIPTOR.message_types_by_name['SpendResult'] = _SPENDRESULT

SpendRequest = _reflection.GeneratedProtocolMessageType('SpendRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPENDREQUEST,
  __module__ = 'Spend_pb2'
  # @@protoc_insertion_point(class_scope:SpendRequest)
  ))
_sym_db.RegisterMessage(SpendRequest)

SpendResult = _reflection.GeneratedProtocolMessageType('SpendResult', (_message.Message,), dict(

  SpendData = _reflection.GeneratedProtocolMessageType('SpendData', (_message.Message,), dict(
    DESCRIPTOR = _SPENDRESULT_SPENDDATA,
    __module__ = 'Spend_pb2'
    # @@protoc_insertion_point(class_scope:SpendResult.SpendData)
    ))
  ,
  DESCRIPTOR = _SPENDRESULT,
  __module__ = 'Spend_pb2'
  # @@protoc_insertion_point(class_scope:SpendResult)
  ))
_sym_db.RegisterMessage(SpendResult)
_sym_db.RegisterMessage(SpendResult.SpendData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
