# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VerificationCode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from pb_src.python_standard import BaseHeaderOut_pb2
from pb_src.python_standard import Product_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VerificationCode.proto',
  package='',
  serialized_pb=_b('\n\x16VerificationCode.proto\x1a\x13\x42\x61seHeaderOut.proto\x1a\rProduct.proto\"\x89\x03\n\x17VerificationCodeRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x18\n\x10VerificationCode\x18\x02 \x02(\t\x12\x14\n\x0cpartnerOrder\x18\x03 \x01(\t\x12\x11\n\tpartnerId\x18\x04 \x01(\t\x12\x0f\n\x07payType\x18\x05 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\t\x12\x11\n\tpayAmount\x18\x07 \x01(\t\x12\x10\n\x08\x63urrency\x18\x08 \x01(\t\x12\x19\n\x07product\x18\t \x01(\x0b\x32\x08.Product\x12\x11\n\treturnUrl\x18\n \x01(\t\x12\x11\n\tnotifyUrl\x18\x0b \x01(\t\x12\x15\n\rpartnerParams\x18\x0c \x01(\t\x12\x14\n\x0c\x65xtendParams\x18\r \x01(\t\x12\x14\n\x0c\x62usinessType\x18\x0e \x01(\t\x12\x19\n\x11\x62usinessChannelId\x18\x0f \x01(\t\x12\x13\n\x0bphoneNumber\x18\x10 \x01(\t\x12\x10\n\x08payReqId\x18\x11 \x01(\t\"\x82\x02\n\x18VerificationCodeResponse\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x44\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x36.VerificationCodeResponse.VerificationCodeResponseData\x1ar\n\x1cVerificationCodeResponseData\x12\x14\n\x0cpayRequestId\x18\x01 \x01(\t\x12\x0e\n\x06payUrl\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\x12\x18\n\x10\x63hannelReturnUrl\x18\x04 \x01(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,Product_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VERIFICATIONCODEREQUEST = _descriptor.Descriptor(
  name='VerificationCodeRequest',
  full_name='VerificationCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='VerificationCodeRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VerificationCode', full_name='VerificationCodeRequest.VerificationCode', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerOrder', full_name='VerificationCodeRequest.partnerOrder', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerId', full_name='VerificationCodeRequest.partnerId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='VerificationCodeRequest.payType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='VerificationCodeRequest.channel', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payAmount', full_name='VerificationCodeRequest.payAmount', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='VerificationCodeRequest.currency', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='VerificationCodeRequest.product', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='returnUrl', full_name='VerificationCodeRequest.returnUrl', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notifyUrl', full_name='VerificationCodeRequest.notifyUrl', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerParams', full_name='VerificationCodeRequest.partnerParams', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extendParams', full_name='VerificationCodeRequest.extendParams', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='businessType', full_name='VerificationCodeRequest.businessType', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='businessChannelId', full_name='VerificationCodeRequest.businessChannelId', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phoneNumber', full_name='VerificationCodeRequest.phoneNumber', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payReqId', full_name='VerificationCodeRequest.payReqId', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=456,
)


_VERIFICATIONCODERESPONSE_VERIFICATIONCODERESPONSEDATA = _descriptor.Descriptor(
  name='VerificationCodeResponseData',
  full_name='VerificationCodeResponse.VerificationCodeResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payRequestId', full_name='VerificationCodeResponse.VerificationCodeResponseData.payRequestId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payUrl', full_name='VerificationCodeResponse.VerificationCodeResponseData.payUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='VerificationCodeResponse.VerificationCodeResponseData.parameters', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channelReturnUrl', full_name='VerificationCodeResponse.VerificationCodeResponseData.channelReturnUrl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=717,
)

_VERIFICATIONCODERESPONSE = _descriptor.Descriptor(
  name='VerificationCodeResponse',
  full_name='VerificationCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='VerificationCodeResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='VerificationCodeResponse.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='VerificationCodeResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='VerificationCodeResponse.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VERIFICATIONCODERESPONSE_VERIFICATIONCODERESPONSEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=717,
)

_VERIFICATIONCODEREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_VERIFICATIONCODEREQUEST.fields_by_name['product'].message_type = Product_pb2._PRODUCT
_VERIFICATIONCODERESPONSE_VERIFICATIONCODERESPONSEDATA.containing_type = _VERIFICATIONCODERESPONSE
_VERIFICATIONCODERESPONSE.fields_by_name['data'].message_type = _VERIFICATIONCODERESPONSE_VERIFICATIONCODERESPONSEDATA
DESCRIPTOR.message_types_by_name['VerificationCodeRequest'] = _VERIFICATIONCODEREQUEST
DESCRIPTOR.message_types_by_name['VerificationCodeResponse'] = _VERIFICATIONCODERESPONSE

VerificationCodeRequest = _reflection.GeneratedProtocolMessageType('VerificationCodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERIFICATIONCODEREQUEST,
  __module__ = 'VerificationCode_pb2'
  # @@protoc_insertion_point(class_scope:VerificationCodeRequest)
  ))
_sym_db.RegisterMessage(VerificationCodeRequest)

VerificationCodeResponse = _reflection.GeneratedProtocolMessageType('VerificationCodeResponse', (_message.Message,), dict(

  VerificationCodeResponseData = _reflection.GeneratedProtocolMessageType('VerificationCodeResponseData', (_message.Message,), dict(
    DESCRIPTOR = _VERIFICATIONCODERESPONSE_VERIFICATIONCODERESPONSEDATA,
    __module__ = 'VerificationCode_pb2'
    # @@protoc_insertion_point(class_scope:VerificationCodeResponse.VerificationCodeResponseData)
    ))
  ,
  DESCRIPTOR = _VERIFICATIONCODERESPONSE,
  __module__ = 'VerificationCode_pb2'
  # @@protoc_insertion_point(class_scope:VerificationCodeResponse)
  ))
_sym_db.RegisterMessage(VerificationCodeResponse)
_sym_db.RegisterMessage(VerificationCodeResponse.VerificationCodeResponseData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
