# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WithholdPay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from pb_src.python_standard import BaseHeaderOut_pb2
from pb_src.python_standard import Product_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WithholdPay.proto',
  package='',
  serialized_pb=_b('\n\x11WithholdPay.proto\x1a\x13\x42\x61seHeaderOut.proto\x1a\rProduct.proto\"\xa5\x03\n\x12WithholdPayRequest\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.BaseHeaderOut\x12\x14\n\x0cpartnerOrder\x18\x02 \x02(\t\x12\x11\n\tpartnerId\x18\x03 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x02(\t\x12\x0f\n\x07payType\x18\x05 \x02(\t\x12\x0f\n\x07\x63hannel\x18\x06 \x02(\t\x12\x11\n\tpayAmount\x18\x07 \x02(\t\x12\x10\n\x08\x63urrency\x18\x08 \x02(\t\x12\x19\n\x07product\x18\x0b \x02(\x0b\x32\x08.Product\x12\x11\n\treturnUrl\x18\x0c \x01(\t\x12\x11\n\tnotifyUrl\x18\r \x01(\t\x12\x15\n\rpartnerParams\x18\x0e \x01(\t\x12\x14\n\x0c\x65xtendParams\x18\x0f \x01(\t\x12\x14\n\x0c\x62usinessType\x18\x10 \x01(\t\x12\x19\n\x11\x62usinessChannelId\x18\x11 \x01(\t\x12\x10\n\x08signFlag\x18\x12 \x01(\x08\x12\x13\n\x0b\x61greementNo\x18\x13 \x01(\t\x12\x15\n\rwalletVersion\x18\x14 \x01(\t\x12\x11\n\tucVersion\x18\x15 \x01(\t\"\xd4\x01\n\x13WithholdPayResponse\x12\x11\n\tisSuccess\x18\x01 \x02(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12:\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32,.WithholdPayResponse.WithholdPayResponseData\x1aS\n\x17WithholdPayResponseData\x12\x14\n\x0cpayRequestId\x18\x01 \x02(\t\x12\x0e\n\x06payUrl\x18\x02 \x02(\t\x12\x12\n\nparameters\x18\x03 \x02(\tB\x13\n\x11\x63om.oppo.pay.bean')
  ,
  dependencies=[BaseHeaderOut_pb2.DESCRIPTOR,Product_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WITHHOLDPAYREQUEST = _descriptor.Descriptor(
  name='WithholdPayRequest',
  full_name='WithholdPayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='WithholdPayRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerOrder', full_name='WithholdPayRequest.partnerOrder', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerId', full_name='WithholdPayRequest.partnerId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='WithholdPayRequest.country', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payType', full_name='WithholdPayRequest.payType', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='WithholdPayRequest.channel', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payAmount', full_name='WithholdPayRequest.payAmount', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='WithholdPayRequest.currency', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='WithholdPayRequest.product', index=8,
      number=11, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='returnUrl', full_name='WithholdPayRequest.returnUrl', index=9,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notifyUrl', full_name='WithholdPayRequest.notifyUrl', index=10,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerParams', full_name='WithholdPayRequest.partnerParams', index=11,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extendParams', full_name='WithholdPayRequest.extendParams', index=12,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='businessType', full_name='WithholdPayRequest.businessType', index=13,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='businessChannelId', full_name='WithholdPayRequest.businessChannelId', index=14,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signFlag', full_name='WithholdPayRequest.signFlag', index=15,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='agreementNo', full_name='WithholdPayRequest.agreementNo', index=16,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='walletVersion', full_name='WithholdPayRequest.walletVersion', index=17,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ucVersion', full_name='WithholdPayRequest.ucVersion', index=18,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=479,
)


_WITHHOLDPAYRESPONSE_WITHHOLDPAYRESPONSEDATA = _descriptor.Descriptor(
  name='WithholdPayResponseData',
  full_name='WithholdPayResponse.WithholdPayResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payRequestId', full_name='WithholdPayResponse.WithholdPayResponseData.payRequestId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payUrl', full_name='WithholdPayResponse.WithholdPayResponseData.payUrl', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='WithholdPayResponse.WithholdPayResponseData.parameters', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=694,
)

_WITHHOLDPAYRESPONSE = _descriptor.Descriptor(
  name='WithholdPayResponse',
  full_name='WithholdPayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='WithholdPayResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='WithholdPayResponse.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='WithholdPayResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='WithholdPayResponse.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WITHHOLDPAYRESPONSE_WITHHOLDPAYRESPONSEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=694,
)

_WITHHOLDPAYREQUEST.fields_by_name['header'].message_type = BaseHeaderOut_pb2._BASEHEADEROUT
_WITHHOLDPAYREQUEST.fields_by_name['product'].message_type = Product_pb2._PRODUCT
_WITHHOLDPAYRESPONSE_WITHHOLDPAYRESPONSEDATA.containing_type = _WITHHOLDPAYRESPONSE
_WITHHOLDPAYRESPONSE.fields_by_name['data'].message_type = _WITHHOLDPAYRESPONSE_WITHHOLDPAYRESPONSEDATA
DESCRIPTOR.message_types_by_name['WithholdPayRequest'] = _WITHHOLDPAYREQUEST
DESCRIPTOR.message_types_by_name['WithholdPayResponse'] = _WITHHOLDPAYRESPONSE

WithholdPayRequest = _reflection.GeneratedProtocolMessageType('WithholdPayRequest', (_message.Message,), dict(
  DESCRIPTOR = _WITHHOLDPAYREQUEST,
  __module__ = 'WithholdPay_pb2'
  # @@protoc_insertion_point(class_scope:WithholdPayRequest)
  ))
_sym_db.RegisterMessage(WithholdPayRequest)

WithholdPayResponse = _reflection.GeneratedProtocolMessageType('WithholdPayResponse', (_message.Message,), dict(

  WithholdPayResponseData = _reflection.GeneratedProtocolMessageType('WithholdPayResponseData', (_message.Message,), dict(
    DESCRIPTOR = _WITHHOLDPAYRESPONSE_WITHHOLDPAYRESPONSEDATA,
    __module__ = 'WithholdPay_pb2'
    # @@protoc_insertion_point(class_scope:WithholdPayResponse.WithholdPayResponseData)
    ))
  ,
  DESCRIPTOR = _WITHHOLDPAYRESPONSE,
  __module__ = 'WithholdPay_pb2'
  # @@protoc_insertion_point(class_scope:WithholdPayResponse)
  ))
_sym_db.RegisterMessage(WithholdPayResponse)
_sym_db.RegisterMessage(WithholdPayResponse.WithholdPayResponseData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.oppo.pay.bean'))
# @@protoc_insertion_point(module_scope)
